services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./src/main/resources/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
  spring-keycloak-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: spring-keycloak-app
    depends_on:
      - postgres
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_USER}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8080/realms/bambino-grande
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/bambino-grande/protocol/openid-connect/certs
      JWT_AUTH_CONVERTER_RESOURCE_ID: bambino-grande-rest-api
      JWT_AUTH_CONVERTER_PRINCIPAL_ATTRIBUTE: sub
    ports:
      - "8081:8080"
    restart: always
    networks:
      - app-network
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge