spring.application.name=bambino-grande_template

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/bambino_grande
spring.datasource.username=bambino_grande
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/bambino-grande
jwt.auth.converter.principal-attribute=sub
jwt.auth.converter.resource-id=bambino-grande-rest-api