spring.application.name=bambino-grande_tests

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost/mock-jwks
jwt.auth.converter.principal-attribute=sub
jwt.auth.converter.resource-id=bambino-grande-rest-api