spring.application.name=order-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5433/order_service
spring.datasource.username=order_service
spring.datasource.password=password

spring.liquibase.change-log=classpath:db/order-service/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.rabbitmq.host = localhost
spring.rabbitmq.port = 5672

storage-service.base-url=http://localhost:8082

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/bambino-grande
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/bambino-grande/protocol/openid-connect/certs
jwt.auth.converter.principal-attribute=sub
jwt.auth.converter.resource-id=bambino-grande-rest-api

outbox.publisher.fixed-delay-ms=1000